name: Build PR

on:
  pull_request

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: set up jdk 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    - name: use gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: current
    - name: build
      run: gradle build

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: set up jdk 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    - name: use gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: current
    - name: build
      run: gradle build

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: set up jdk 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    - name: use gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: current
    - name: build
      run: gradle build
