name: Build PR

on:
  pull_request

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    - name: use gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: current
    - name: build
      run: gradle build

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    - name: use gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: current
    - name: build
      run: gradle build

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    - name: use gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: current
    - name: build
      run: gradle build

