name: Gradle Build

on:
  push

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}

    - name: use gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: current

    - name: build
      run: gradle build

    - name: jpackage
      run: gradle jpackage

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos (.dmg)
        path: ${{ github.workspace }}/Graphedit/build/jpackage/*.dmg


  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}

    - name: use gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: current

    - name: build
      run: gradle build

    - name: jpackage
      run: gradle jpackage

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows (.msi)
        path: ${{ github.workspace }}/Graphedit/build/jpackage/*.msi

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}

    - name: use gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: current

    - name: install build dependencies
      run: sudo apt-get update && sudo apt-get install -y binutils dpkg dpkg-dev git fakeroot rpm make imagemagick inkscape

    - name: create icon
      run: make linuxIcon

    - name: build
      run: gradle build

    - name: jpackage
      run: gradle jpackage

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debian or ubuntu (.deb)
        path: ${{ github.workspace }}/Graphedit/build/jpackage/*.deb

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: redhat (.rpm)
        path: ${{ github.workspace }}/Graphedit/build/jpackage/*.rpm

